src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Genie\Giniesschema\Schema\Http\Controllers\ConnectionController;
use Genie\Giniesschema\Schema\Http\Controllers\TableController;
use Genie\Giniesschema\Schema\Http\Controllers\StructureController;

use Genie\Giniesschema\Schema\Http\Controllers\ConstraintController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('connections', ConnectionController::class);
	Route::resource('tables', TableController::class);
	Route::resource('structures', StructureController::class);
	Route::resource('constraints', ConstraintController::class);
	Route::get('/columns/{key}',[StructureController::class, 'structure'])->name('structure');
	Route::get('/editablestructure/{key}',[StructureController::class, 'editablestructure'])->name('editablestructure');
	Route::post('/editablestructure',[StructureController::class, 'editablestructurestore'])->name('editablestructure.store');
	Route::get('/json-structure/{key}',[StructureController::class, 'jsonStructure'])->name('structures.json');
	Route::get('/table/{key}',[TableController::class, 'tables'])->name('table');

	Route::post('create-json', [StructureController::class, 'createJson'])->name('create_json');
	Route::post('store', [StructureController::class, 'store'])->name('json_store');


//Place your route here
});

src/Models/Connection.php
<?php

namespace Genie\Giniesschema\Schema\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;



use App\Traits\Historiable;

class Connection extends Model
{
    
    use SoftDeletes;
    
    
    use Historiable;
    protected $connection = 'oracle';
    protected $table = 'connections';
    protected $guarded = ['id'];
    

    /**
    * Get the route key for the model.
    *
    * @return string
    */
    public function getRouteKeyName()
    {
        return 'uuid';
    }

    ##ELOQUENTRELATIONSHIPMODEL##
}

src/Http/Controllers/Api/ConnectionController.php
<?php

namespace Genie\Giniesschema\Schema\Http\Controllers\Api;

class ConnectionController extends ConnectionBaseController
{

}

src/Http/Controllers/ConnectionController.php
<?php

namespace Genie\Giniesschema\Schema\Http\Controllers;
use App\Http\Controllers\Controller;
use Genie\Giniesschema\Schema\Http\Requests\ConnectionRequest;
use Genie\Giniesschema\Schema\Models\Connection;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ConnectionController extends ConnectionBaseController
{
    public function index()
    {
        $schema = DB::connection()->getDoctrineSchemaManager();
        $connections = $schema->listDatabases();
        return view('schema::connections.index', compact('connections'));
    }
    
    public function store(ConnectionRequest $request)
    {
        try {
            $connection = Connection::create(['uuid'=>(string) Str::uuid()] + $request->all());
            //handle relationship store
            return redirect()->route('connections.index')
                ->withSuccess(__('Successfully Created'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }
}

src/resources/views/connections/create.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Connection') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('connections.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <x-forms.select-connection :attributes="['name' => 'householdtype', 'class' => 'form-control select', 'id' => 'householdtype']" :selected="old('')" />
                    <x-sg-alert-errors name="householdtype" />
                <div class="row">
                {{--relationalFields--}}

                    <!-- title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="titleInput">{{ __('Title') }}</x-sg-label>
        <x-sg-text type="text" id="titleInput" name="title" :value="old('title')" placeholder="" />
        <x-sg-alert-errors name="title" />
    </div>
</div>

<!-- host_db -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="host_dbInput">{{ __('Host Db') }}</x-sg-label>
        <x-sg-text type="text" id="host_dbInput" name="host_db" :value="old('host_db')" placeholder="" />
        <x-sg-alert-errors name="host_db" />
    </div>
</div>

<!-- user -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="userInput">{{ __('User') }}</x-sg-label>
        <x-sg-text type="text" id="userInput" name="user" :value="old('user')" placeholder="" />
        <x-sg-alert-errors name="user" />
    </div>
</div>

<!-- password -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="passwordInput">{{ __('Password') }}</x-sg-label>
        <x-sg-text type="text" id="passwordInput" name="password" :value="old('password')" placeholder="" />
        <x-sg-alert-errors name="password" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('connections.index')}}" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/connections/edit.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Connection') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('connections.update', $connection->uuid) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="row">
                    {{--relationalFields--}}
                    <!-- title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="titleInput">{{ __('Title') }}</x-sg-label>
        <x-sg-text type="text" id="titleInput" name="title" :value="old('title', $connection->title)" placeholder="" />
        <x-sg-alert-errors name="title" />
    </div>
</div>

<!-- host_db -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="host_dbInput">{{ __('Host Db') }}</x-sg-label>
        <x-sg-text type="text" id="host_dbInput" name="host_db" :value="old('host_db', $connection->host_db)" placeholder="" />
        <x-sg-alert-errors name="host_db" />
    </div>
</div>

<!-- user -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="userInput">{{ __('User') }}</x-sg-label>
        <x-sg-text type="text" id="userInput" name="user" :value="old('user', $connection->user)" placeholder="" />
        <x-sg-alert-errors name="user" />
    </div>
</div>

<!-- password -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="passwordInput">{{ __('Password') }}</x-sg-label>
        <x-sg-text type="text" id="passwordInput" name="password" :value="old('password', $connection->password)" placeholder="" />
        <x-sg-alert-errors name="password" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('connections.index')}}" />
        </x-slot>
    </x-sg-card>
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/connections/index.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Connection') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-message :message="session('success')" type="success" />
            <x-sg-table type="basic"  id="connectionDatatable">
                <x-sg-thead>
                    <tr>
                        <th>{{ __('SL') }}</th>
                        <th>{{ __('Title') }}</th>
						<th>{{ __('Host Db') }}</th>
						<th>{{ __('User') }}</th>

                        <th>{{ __('Actions' )}}</th>
                    </tr>
                </x-sg-thead>
                <x-sg-tbody>
                    @foreach ($connections as $key=>$connection)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $connection}}</td>
						<td></td>
						<td></td>

                        <td>
                        <x-sg-link-show href="{{route('table', $key)}}" />
                            
                        </td>
                    </tr>
                    @endforeach
                </x-sg-tbody>
            </x-sg-table>
        </x-slot>
        <x-slot name="cardFooterCenter">

            <x-sg-link-create href="{{route('connections.create')}}" />

        </x-slot>
    </x-sg-card>



@push('js')


<script>
   $(document).ready(function() {
        $('#connectionDatatable').DataTable({
            buttons: [
                {
                    extend: 'colvis',
                    text: '<i class="icon-grid3"></i>',
                    className: 'btn bg-indigo-400 btn-icon dropdown-toggle'
                }
            ],
            stateSave: false,
            columnDefs: [
                {
                    targets: 0,
                    visible: true
                }
            ]
        });
    });
</script>
@endpush

</x-sg-master>

src/resources/views/connections/show.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Connection') }}
        </x-slot>
        <x-slot name="body">
            <p><b>{{ __('Title') }} : </b> {{ $connection->title }}</p>
			<p><b>{{ __('Host Db') }} : </b> {{ $connection->host_db }}</p>
			<p><b>{{ __('User') }} : </b> {{ $connection->user }}</p>
			<p><b>{{ __('Password') }} : </b> {{ $connection->password }}</p>
			
            {{--othersInfo--}}
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-create href="{{route('connections.index')}}" />
            <x-sg-link-list href="{{route('connections.index')}}" />
            <x-sg-link-edit href="{{route('connections.edit',$connection->uuid)}}" />
            <x-sg-link-history uuid="{{$connection->uuid}}" api="/api/connections-histories-list" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
</x-sg-master>