src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Genie\Giniesschema\Schema\Http\Controllers\ConnectionController;
use Genie\Giniesschema\Schema\Http\Controllers\TableController;
use Genie\Giniesschema\Schema\Http\Controllers\StructureController;

use Genie\Giniesschema\Schema\Http\Controllers\ConstraintController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('connections', ConnectionController::class);
	Route::resource('tables', TableController::class);
	Route::resource('structures', StructureController::class);
	Route::resource('constraints', ConstraintController::class);
	Route::get('/columns/{key}',[StructureController::class, 'structure'])->name('structure');
	Route::get('/editablestructure/{key}',[StructureController::class, 'editablestructure'])->name('editablestructure');
	Route::post('/editablestructure',[StructureController::class, 'editablestructurestore'])->name('editablestructure.store');
	Route::get('/json-structure/{key}',[StructureController::class, 'jsonStructure'])->name('structures.json');
	Route::get('/table/{key}',[TableController::class, 'tables'])->name('table');

	Route::post('create-json', [StructureController::class, 'createJson'])->name('create_json');
	Route::post('store', [StructureController::class, 'store'])->name('json_store');


//Place your route here
});

src/Models/Constraint.php
<?php

namespace Genie\Giniesschema\Schema\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\UserTrackable;


use App\Traits\Historiable;

class Constraint extends Model
{
    use UserTrackable;
    use SoftDeletes;
    
    
    use Historiable;
    protected $connection = 'oracle';
    protected $table = 'constraints';
    protected $guarded = ['id'];
    

    /**
    * Get the route key for the model.
    *
    * @return string
    */
    public function getRouteKeyName()
    {
        return 'uuid';
    }

    ##ELOQUENTRELATIONSHIPMODEL##
}

src/Http/Controllers/Api/ConstraintController.php
<?php

namespace Genie\Giniesschema\Schema\Http\Controllers\Api;

class ConstraintController extends ConstraintBaseController
{

}

src/Http/Controllers/ConstraintController.php
<?php

namespace Genie\Giniesschema\Schema\Http\Controllers;

class ConstraintController extends ConstraintBaseController
{

}

src/resources/views/constraints/create.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Constraint') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('constraints.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">
                {{--relationalFields--}}

                    <!-- key_name -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="key_nameInput">{{ __('Key Name') }}</x-sg-label>
        <x-sg-text type="text" id="key_nameInput" name="key_name" :value="old('key_name')" placeholder="" />
        <x-sg-alert-errors name="key_name" />
    </div>
</div>

<!-- type -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="typeInput">{{ __('Type') }}</x-sg-label>
        <x-sg-text type="text" id="typeInput" name="type" :value="old('type')" placeholder="" />
        <x-sg-alert-errors name="type" />
    </div>
</div>

<!-- unique -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="uniqueInput">{{ __('Unique') }}</x-sg-label>
        <x-sg-text type="text" id="uniqueInput" name="unique" :value="old('unique')" placeholder="" />
        <x-sg-alert-errors name="unique" />
    </div>
</div>

<!-- packed -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="packedInput">{{ __('Packed') }}</x-sg-label>
        <x-sg-text type="text" id="packedInput" name="packed" :value="old('packed')" placeholder="" />
        <x-sg-alert-errors name="packed" />
    </div>
</div>

<!-- column -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="columnInput">{{ __('Column') }}</x-sg-label>
        <x-sg-text type="text" id="columnInput" name="column" :value="old('column')" placeholder="" />
        <x-sg-alert-errors name="column" />
    </div>
</div>

<!-- cardinality -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="cardinalityInput">{{ __('Cardinality') }}</x-sg-label>
        <x-sg-text type="text" id="cardinalityInput" name="cardinality" :value="old('cardinality')" placeholder="" />
        <x-sg-alert-errors name="cardinality" />
    </div>
</div>

<!-- collation -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="collationInput">{{ __('Collation') }}</x-sg-label>
        <x-sg-text type="text" id="collationInput" name="collation" :value="old('collation')" placeholder="" />
        <x-sg-alert-errors name="collation" />
    </div>
</div>

<!-- null -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="nullInput">{{ __('Null') }}</x-sg-label>
        <x-sg-text type="text" id="nullInput" name="null" :value="old('null')" placeholder="" />
        <x-sg-alert-errors name="null" />
    </div>
</div>

<!-- comment -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="commentInput">{{ __('Comment') }}</x-sg-label>
        <x-sg-text type="text" id="commentInput" name="comment" :value="old('comment')" placeholder="" />
        <x-sg-alert-errors name="comment" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('constraints.index')}}" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/constraints/edit.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Constraint') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('constraints.update', $constraint->uuid) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="row">
                    {{--relationalFields--}}
                    <!-- key_name -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="key_nameInput">{{ __('Key Name') }}</x-sg-label>
        <x-sg-text type="text" id="key_nameInput" name="key_name" :value="old('key_name', $constraint->key_name)" placeholder="" />
        <x-sg-alert-errors name="key_name" />
    </div>
</div>

<!-- type -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="typeInput">{{ __('Type') }}</x-sg-label>
        <x-sg-text type="text" id="typeInput" name="type" :value="old('type', $constraint->type)" placeholder="" />
        <x-sg-alert-errors name="type" />
    </div>
</div>

<!-- unique -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="uniqueInput">{{ __('Unique') }}</x-sg-label>
        <x-sg-text type="text" id="uniqueInput" name="unique" :value="old('unique', $constraint->unique)" placeholder="" />
        <x-sg-alert-errors name="unique" />
    </div>
</div>

<!-- packed -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="packedInput">{{ __('Packed') }}</x-sg-label>
        <x-sg-text type="text" id="packedInput" name="packed" :value="old('packed', $constraint->packed)" placeholder="" />
        <x-sg-alert-errors name="packed" />
    </div>
</div>

<!-- column -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="columnInput">{{ __('Column') }}</x-sg-label>
        <x-sg-text type="text" id="columnInput" name="column" :value="old('column', $constraint->column)" placeholder="" />
        <x-sg-alert-errors name="column" />
    </div>
</div>

<!-- cardinality -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="cardinalityInput">{{ __('Cardinality') }}</x-sg-label>
        <x-sg-text type="text" id="cardinalityInput" name="cardinality" :value="old('cardinality', $constraint->cardinality)" placeholder="" />
        <x-sg-alert-errors name="cardinality" />
    </div>
</div>

<!-- collation -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="collationInput">{{ __('Collation') }}</x-sg-label>
        <x-sg-text type="text" id="collationInput" name="collation" :value="old('collation', $constraint->collation)" placeholder="" />
        <x-sg-alert-errors name="collation" />
    </div>
</div>

<!-- null -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="nullInput">{{ __('Null') }}</x-sg-label>
        <x-sg-text type="text" id="nullInput" name="null" :value="old('null', $constraint->null)" placeholder="" />
        <x-sg-alert-errors name="null" />
    </div>
</div>

<!-- comment -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="commentInput">{{ __('Comment') }}</x-sg-label>
        <x-sg-text type="text" id="commentInput" name="comment" :value="old('comment', $constraint->comment)" placeholder="" />
        <x-sg-alert-errors name="comment" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('constraints.index')}}" />
        </x-slot>
    </x-sg-card>
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/constraints/index.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Constraint') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-message :message="session('success')" type="success" />
            <x-sg-table type="basic"  id="constraintDatatable">
                <x-sg-thead>
                    <tr>
                        <th>{{ __('SL') }}</th>
                            						<th>{{ __('Key Name') }}</th>
						<th>{{ __('Type') }}</th>
						<th>{{ __('Unique') }}</th>
						<th>{{ __('Packed') }}</th>
						<th>{{ __('Column') }}</th>
						<th>{{ __('Cardinality') }}</th>
						<th>{{ __('Collation') }}</th>
						<th>{{ __('Comment') }}</th>

                        <th>{{ __('Actions' )}}</th>
                    </tr>
                </x-sg-thead>
                <x-sg-tbody>
                    @foreach ($constraints as $constraint)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        						<td>{{ $constraint->key_name }}</td>
						<td>{{ $constraint->type }}</td>
						<td>{{ $constraint->unique }}</td>
						<td>{{ $constraint->packed }}</td>
						<td>{{ $constraint->column }}</td>
						<td>{{ $constraint->cardinality }}</td>
						<td>{{ $constraint->collation }}</td>
						<td>{{ $constraint->comment }}</td>

                        <td>
                            <x-sg-link-show href="{{route('constraints.show', $constraint->uuid)}}" />
                            <x-sg-link-edit href="{{route('constraints.edit', $constraint->uuid)}}" />
                            <x-sg-btn-delete action="{{route('constraints.destroy', $constraint->uuid)}}" method="post" />
                            <x-sg-link-history uuid="{{ $constraint->uuid }}"  api="/api/constraint-histories-list" />
                        </td>
                    </tr>
                    @endforeach
                </x-sg-tbody>
            </x-sg-table>
        </x-slot>
        <x-slot name="cardFooterCenter">

            <x-sg-link-create href="{{route('constraints.create')}}" />

        </x-slot>
    </x-sg-card>



@push('js')


<script>
   $(document).ready(function() {
        $('#constraintDatatable').DataTable({
            buttons: [
                {
                    extend: 'colvis',
                    text: '<i class="icon-grid3"></i>',
                    className: 'btn bg-indigo-400 btn-icon dropdown-toggle'
                }
            ],
            stateSave: false,
            columnDefs: [
                {
                    targets: 0,
                    visible: true
                }
            ]
        });
    });
</script>
@endpush

</x-sg-master>

src/resources/views/constraints/show.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Constraint') }}
        </x-slot>
        <x-slot name="body">
            <p><b>{{ __('Key Name') }} : </b> {{ $constraint->key_name }}</p>
			<p><b>{{ __('Type') }} : </b> {{ $constraint->type }}</p>
			<p><b>{{ __('Unique') }} : </b> {{ $constraint->unique }}</p>
			<p><b>{{ __('Packed') }} : </b> {{ $constraint->packed }}</p>
			<p><b>{{ __('Column') }} : </b> {{ $constraint->column }}</p>
			<p><b>{{ __('Cardinality') }} : </b> {{ $constraint->cardinality }}</p>
			<p><b>{{ __('Collation') }} : </b> {{ $constraint->collation }}</p>
			<p><b>{{ __('Null') }} : </b> {{ $constraint->null }}</p>
			<p><b>{{ __('Comment') }} : </b> {{ $constraint->comment }}</p>
			
            {{--othersInfo--}}
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-create href="{{route('constraints.index')}}" />
            <x-sg-link-list href="{{route('constraints.index')}}" />
            <x-sg-link-edit href="{{route('constraints.edit',$constraint->uuid)}}" />
            <x-sg-link-history uuid="{{$constraint->uuid}}" api="/api/constraints-histories-list" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
</x-sg-master>